const fs = require('fs');
const path = require('path');

const file = path.join(__dirname, '../services/translations.ts');
let content = fs.readFileSync(file, 'utf8');

const rawKeys = {
  es: {
    guide_cpr_title: "Seguridad y RCP",
    guide_cpr_subtitle: "Protocolos Vitales",
    cpr_intro: "Nadie quiere pensar en emergencias, pero estar preparado salva vidas. Memoriza estos pasos por si alguna vez los necesitas.",
    cpr_choking_title: "Atragantamiento (Heimlich Bebés)",
    cpr_choking_desc: "Si el bebé no puede toser, llorar o respirar, y se pone azul, actúa inmediatamente.",
    cpr_choking_step_1: "Pon al bebé boca abajo sobre tu antebrazo, sujetando su mandíbula (no el cuello).",
    cpr_choking_step_2: "Da 5 palmadas firmes en la espalda, entre los omóplatos, con el talón de la otra mano.",
    cpr_choking_step_3: "Dale la vuelta. Si no ha expulsado el objeto, da 5 compresiones rápidas en el centro del pecho con dos dedos.",
    cpr_choking_step_4: "Repite el ciclo de 5 palmadas y 5 compresiones hasta que el objeto salga o el bebé llore.",
    cpr_cpr_title: "Reanimación Cardiopulmonar (RCP)",
    cpr_cpr_desc: "Si el bebé no respira y no responde a estímulos, comienza la RCP básica.",
    cpr_cpr_ratio: "Ciclo: 5 ventilaciones, luego 15 compresiones / 2 ventilaciones",
    cpr_cpr_step_1: "Comienza con 5 ventilaciones de rescate (cubre su boca y nariz con tu boca, sopla suave).",
    cpr_cpr_step_2: "Haz 15 compresiones en el centro del pecho con dos dedos (un tercio del tórax de profundidad).",
    cpr_cpr_step_3: "Aplica 2 ventilaciones. Repite 15:2 sin parar hasta que llegue ayuda.",
    cpr_emergency_title: "Llamada de Emergencia",
    cpr_emergency_desc: "En Europa marca el 112. Pon el manos libres mientras realizas las maniobras.",
    cpr_disclaimer: "Esta guía es informativa. Se recomienda encarecidamente realizar un curso práctico de primeros auxilios pediátricos.",
    
    guide_babywearing_title: "Porteo Ergonómico",
    guide_babywearing_subtitle: "Manos Libres, Corazón Cerca",
    wearing_intro: "El porteo facilita la vida, calma los cólicos y mejora el vínculo. Pero debe ser ergonómico para proteger su desarrollo.",
    wearing_ergo_title: "Postura Correcta",
    wearing_ergo_desc: "Un porteo seguro y respetuoso debe cumplir estas tres reglas de oro:",
    wearing_ergo_m: "Las rodillas deben estar más altas que el culito.",
    wearing_ergo_c: "La espalda debe mantener su curvatura natural.",
    wearing_ergo_kiss: "La barbilla del bebé no debe tocar su pecho (vías libres) y debes poder darle un beso en la cabeza.",
    wearing_types_title: "Tipos de Portabebés",
    wearing_type_wrap_title: "Fular Elástico",
    wearing_type_wrap_desc: "Ideal para recién nacidos. Es como una camiseta ajustada.",
    wearing_type_backpack_title: "Mochila Ergonómica",
    wearing_type_backpack_desc: "Fácil de poner. Asegúrate de que el panel llegue de rodilla a rodilla.",
    wearing_type_ring_title: "Bandolera de Anillas",
    wearing_type_ring_desc: "Asimétrica, ideal para ratos cortos y subir/bajar rápido.",
    wearing_warning_title: "Precaución",
    wearing_warning_desc: "Evita las mochilas 'colgonas' donde el bebé va mirando hacia adelante. Sobrecargan sus genitales y curvan su espalda de forma antinatural.",

    guide_blw_title: "Alimentación BLW",
    guide_blw_subtitle: "Baby-Led Weaning",
    blw_intro: "Introducir sólidos es una aventura. El BLW fomenta su autonomía, motricidad y relación sana con la comida.",
    blw_requisites_title: "Requisitos para Empezar",
    blw_requisites_desc: "No mires el calendario (6 meses), mira a tu bebé. Debe cumplir estos tres hitos:",
    blw_req_1: "Se mantiene sentado por sí solo (o con apoyo mínimo).",
    blw_req_2: "Ha perdido el reflejo de extrusión (no escupe todo con la lengua).",
    blw_req_3: "Muestra interés activo por la comida de los adultos.",
    blw_gagging_title: "Arcada vs Atragantamiento",
    blw_gagging_desc: "Saber diferenciarlos te dará tranquilidad.",
    blw_arcada_title: "La Arcada (Normal y Segura)",
    blw_arcada_desc: "El bebé hace ruido, tose, se pone rojo y expulsa la comida. Es su mecanismo de defensa. NO interfieras, ni le metas el dedo.",
    blw_choking_title: "El Atragantamiento (Peligro)",
    blw_choking_desc: "El bebé NO hace ruido, se pone morado/azul, cara de pánico. Requiere maniobra de Heimlich inmediata.",
    blw_cuts_title: "Cortes Seguros",
    blw_cuts_desc: "Al principio, los cortes deben ser grandes, como un dedo índice tuyo.",
    blw_cuts_1: "Alimentos blandos (que puedas aplastar con tus dedos).",
    blw_cuts_2: "Evita siempre: salchichas en rodajas, uvas enteras, frutos secos enteros, palomitas, miel (riesgo de botulismo).",

    guide_signing_title: "Baby Signing",
    guide_signing_subtitle: "Comunicación Temprana",
    sign_intro: "Los bebés entienden y quieren comunicarse mucho antes de poder hablar. Enséñales gestos para reducir su frustración.",
    sign_why_title: "¿Por qué funciona?",
    sign_why_desc: "El control motor de las manos se desarrolla antes que las cuerdas vocales.",
    sign_why_quote: "Un bebé que puede pedir 'leche' con las manos, es un bebé que no necesita llorar para pedirla.",
    sign_basic_title: "Primeros Signos",
    sign_milk_title: "Leche",
    sign_milk_desc: "Abrir y cerrar el puño repetidamente (como ordeñando).",
    sign_more_title: "Más",
    sign_more_desc: "Juntar las yemas de los dedos de ambas manos repetidamente.",
    sign_eat_title: "Comer",
    sign_eat_desc: "Llevar la mano junta hacia la boca.",
    sign_tips_title: "Consejos para el Éxito",
    sign_tip_1: "Repite el signo cada vez que digas la palabra.",
    sign_tip_2: "Usa el signo en contexto (haz 'leche' justo antes de dársela).",
    sign_tip_3: "Ten paciencia. Pueden tardar meses en devolver el primer signo."
  },
  en: {
    guide_cpr_title: "Safety & CPR",
    guide_cpr_subtitle: "Vital Protocols",
    cpr_intro: "No one wants to think about emergencies, but being prepared saves lives. Memorize these steps just in case.",
    cpr_choking_title: "Choking (Infant Heimlich)",
    cpr_choking_desc: "If the baby cannot cough, cry, or breathe, and turns blue, act immediately.",
    cpr_choking_step_1: "Place the baby face down on your forearm, supporting their jaw (not neck).",
    cpr_choking_step_2: "Give 5 firm back blows between the shoulder blades with the heel of your hand.",
    cpr_choking_step_3: "Turn them over. If the object hasn't cleared, give 5 quick chest thrusts with two fingers.",
    cpr_choking_step_4: "Repeat 5 blows and 5 thrusts until the object clears or the baby cries.",
    cpr_cpr_title: "Cardiopulmonary Resuscitation (CPR)",
    cpr_cpr_desc: "If the baby is not breathing and unresponsive, begin basic CPR.",
    cpr_cpr_ratio: "Cycle: 5 initial breaths, then 15 compressions / 2 breaths",
    cpr_cpr_step_1: "Start with 5 rescue breaths (cover their mouth and nose with yours, blow gently).",
    cpr_cpr_step_2: "Give 15 chest compressions in the center of the chest with two fingers.",
    cpr_cpr_step_3: "Give 2 breaths. Repeat 15:2 continuously until help arrives.",
    cpr_emergency_title: "Emergency Call",
    cpr_emergency_desc: "In Europe dial 112, US 911. Put it on speakerphone while performing maneuvers.",
    cpr_disclaimer: "This guide is for informational purposes. Taking a practical pediatric first aid course is highly recommended.",
    
    guide_babywearing_title: "Ergonomic Babywearing",
    guide_babywearing_subtitle: "Hands Free, Heart Close",
    wearing_intro: "Babywearing makes life easier, soothes colic, and improves bonding. But it must be ergonomic.",
    wearing_ergo_title: "Correct Posture",
    wearing_ergo_desc: "A safe carry must meet these three golden rules:",
    wearing_ergo_m: "Knees should be higher than the bottom ('M' shape).",
    wearing_ergo_c: "The back should maintain its natural 'C' curve.",
    wearing_ergo_kiss: "The chin shouldn't touch their chest (airways clear), and you should be able to kiss their head.",
    wearing_types_title: "Carrier Types",
    wearing_type_wrap_title: "Stretchy Wrap",
    wearing_type_wrap_desc: "Ideal for newborns. It's like a tight t-shirt.",
    wearing_type_backpack_title: "Ergonomic Carrier",
    wearing_type_backpack_desc: "Easy to put on. Ensure the panel goes from knee to knee.",
    wearing_type_ring_title: "Ring Sling",
    wearing_type_ring_desc: "Asymmetrical, great for short periods and quick ups/downs.",
    wearing_warning_title: "Caution",
    wearing_warning_desc: "Avoid 'crotch-dangler' carriers facing outward. They overload genitals and unnaturally curve the back.",

    guide_blw_title: "BLW Feeding",
    guide_blw_subtitle: "Baby-Led Weaning",
    blw_intro: "Introducing solids is an adventure. BLW fosters autonomy, motor skills, and a healthy relationship with food.",
    blw_requisites_title: "Requirements to Start",
    blw_requisites_desc: "Don't just look at the calendar (6 months), look at your baby. They must meet these three milestones:",
    blw_req_1: "Can sit up on their own (or with minimal support).",
    blw_req_2: "Has lost the extrusion reflex (doesn't spit everything out with their tongue).",
    blw_req_3: "Shows active interest in adult food.",
    blw_gagging_title: "Gagging vs Choking",
    blw_gagging_desc: "Knowing the difference will give you peace of mind.",
    blw_arcada_title: "Gagging (Normal & Safe)",
    blw_arcada_desc: "The baby makes noise, coughs, turns red, and expels the food. It's their defense. DO NOT interfere.",
    blw_choking_title: "Choking (Danger)",
    blw_choking_desc: "The baby makes NO noise, turns blue/purple, panicked face. Requires immediate Heimlich maneuver.",
    blw_cuts_title: "Safe Cuts",
    blw_cuts_desc: "At first, cuts should be large, like the size of your index finger.",
    blw_cuts_1: "Soft foods (you can squash them with your fingers).",
    blw_cuts_2: "Always avoid: sliced hot dogs, whole grapes, whole nuts, popcorn, honey (botulism risk).",

    guide_signing_title: "Baby Signing",
    guide_signing_subtitle: "Early Communication",
    sign_intro: "Babies understand and want to communicate long before they can speak. Teach them gestures to reduce frustration.",
    sign_why_title: "Why it works",
    sign_why_desc: "Motor control of the hands develops before the vocal cords.",
    sign_why_quote: "A baby who can ask for 'milk' with their hands is a baby who doesn't need to cry for it.",
    sign_basic_title: "First Signs",
    sign_milk_title: "Milk",
    sign_milk_desc: "Open and close the fist repeatedly (like milking).",
    sign_more_title: "More",
    sign_more_desc: "Tap the fingertips of both hands together repeatedly.",
    sign_eat_title: "Eat",
    sign_eat_desc: "Bring gathered fingers to the mouth.",
    sign_tips_title: "Tips for Success",
    sign_tip_1: "Repeat the sign every time you say the word.",
    sign_tip_2: "Use the sign in context (sign 'milk' right before giving it).",
    sign_tip_3: "Be patient. It may take months for them to sign back."
  },
  fr: {
    guide_cpr_title: "Sécurité et RCR",
    guide_cpr_subtitle: "Protocoles Vitaux",
    cpr_intro: "Personne ne veut penser aux urgences, mais être préparé sauve des vies.",
    cpr_choking_title: "Étouffement (Heimlich bébé)",
    cpr_choking_desc: "Si le bébé ne peut ni tousser, ni pleurer, ni respirer, agissez immédiatement.",
    cpr_choking_step_1: "Placez le bébé face vers le bas sur votre avant-bras.",
    cpr_choking_step_2: "Donnez 5 claques fermes dans le dos.",
    cpr_choking_step_3: "Retournez-le et donnez 5 compressions thoraciques rapides avec deux doigts.",
    cpr_choking_step_4: "Répétez jusqu'à ce que l'objet soit expulsé.",
    cpr_cpr_title: "Réanimation Cardiorespiratoire (RCR)",
    cpr_cpr_desc: "Si le bébé ne respire pas, commencez la RCR.",
    cpr_cpr_ratio: "Cycle : 5 insufflations, puis 15 compressions / 2 insufflations",
    cpr_cpr_step_1: "Commencez par 5 insufflations (bouche à bouche-nez).",
    cpr_cpr_step_2: "Faites 15 compressions au centre de la poitrine.",
    cpr_cpr_step_3: "Faites 2 insufflations. Répétez le cycle 15:2.",
    cpr_emergency_title: "Appel d'urgence",
    cpr_emergency_desc: "Appelez le 112 en Europe. Mettez le haut-parleur.",
    cpr_disclaimer: "Cette guide est informative. Un cours pratique est recommandé.",
    
    guide_babywearing_title: "Portage Ergonomique",
    guide_babywearing_subtitle: "Mains Libres, Cœur Proche",
    wearing_intro: "Le portage facilite la vie et apaise les coliques, mais il doit être ergonomique.",
    wearing_ergo_title: "Posture Correcte",
    wearing_ergo_desc: "Règles d'or d'un portage sûr :",
    wearing_ergo_m: "Les genoux plus hauts que les fesses (forme en 'M').",
    wearing_ergo_c: "Le dos doit conserver sa courbe naturelle en 'C'.",
    wearing_ergo_kiss: "Le menton ne doit pas toucher la poitrine (voies libres).",
    wearing_types_title: "Types de Porte-bébés",
    wearing_type_wrap_title: "Écharpe Extensible",
    wearing_type_wrap_desc: "Idéal pour les nouveau-nés.",
    wearing_type_backpack_title: "Porte-bébé Ergonomique",
    wearing_type_backpack_desc: "Facile à enfiler. Assurez-vous que le tissu aille de genou à genou.",
    wearing_type_ring_title: "Sling à Anneaux",
    wearing_type_ring_desc: "Asymétrique, idéal pour de courtes durées.",
    wearing_warning_title: "Attention",
    wearing_warning_desc: "Évitez les porte-bébés non physiologiques face au monde.",

    guide_blw_title: "Alimentation DME",
    guide_blw_subtitle: "Diversification Menée par l'Enfant",
    blw_intro: "La DME favorise l'autonomie et une relation saine avec la nourriture.",
    blw_requisites_title: "Conditions requises",
    blw_requisites_desc: "Le bébé doit avoir 6 mois ET répondre à ces trois critères :",
    blw_req_1: "Il tient assis seul (ou avec très peu de soutien).",
    blw_req_2: "Il a perdu le réflexe d'extrusion.",
    blw_req_3: "Il montre de l'intérêt pour votre nourriture.",
    blw_gagging_title: "Réflexe Nauséeux vs Étouffement",
    blw_gagging_desc: "Savoir les différencier vous rassurera.",
    blw_arcada_title: "Réflexe Nauséeux (Normal)",
    blw_arcada_desc: "Le bébé fait du bruit, tousse, devient rouge. N'intervenez PAS.",
    blw_choking_title: "Étouffement (Danger)",
    blw_choking_desc: "Pas de bruit, bébé devient bleu. Manœuvre de Heimlich immédiate.",
    blw_cuts_title: "Coupes Sécuritaires",
    blw_cuts_desc: "Les morceaux doivent être gros (taille de votre index).",
    blw_cuts_1: "Aliments tendres (écrasables entre vos doigts).",
    blw_cuts_2: "À éviter : saucisses en rondelles, raisins entiers, noix, miel.",

    guide_signing_title: "Langue des Signes Bébé",
    guide_signing_subtitle: "Communication Précoce",
    sign_intro: "Enseignez-leur des gestes pour réduire leur frustration avant l'arrivée de la parole.",
    sign_why_title: "Pourquoi ça marche ?",
    sign_why_desc: "Le contrôle moteur des mains se développe avant les cordes vocales.",
    sign_why_quote: "Un bébé qui peut demander du lait avec ses mains n'a pas besoin de pleurer.",
    sign_basic_title: "Premiers Signes",
    sign_milk_title: "Lait",
    sign_milk_desc: "Ouvrir et fermer le poing (comme pour traire).",
    sign_more_title: "Encore",
    sign_more_desc: "Joindre le bout des doigts des deux mains.",
    sign_eat_title: "Manger",
    sign_eat_desc: "Porter la main jointe à la bouche.",
    sign_tips_title: "Conseils",
    sign_tip_1: "Répétez le signe chaque fois que vous dites le mot.",
    sign_tip_2: "Faites le signe en contexte.",
    sign_tip_3: "Soyez patient."
  },
  de: {
    guide_cpr_title: "Sicherheit & HLW",
    guide_cpr_subtitle: "Lebensrettende Protokolle",
    cpr_intro: "Niemand denkt gerne an Notfälle, aber Vorbereitung rettet Leben.",
    cpr_choking_title: "Verschlucken (Heimlich bei Babys)",
    cpr_choking_desc: "Wenn das Baby nicht husten, weinen oder atmen kann, handeln Sie sofort.",
    cpr_choking_step_1: "Legen Sie das Baby mit dem Gesicht nach unten auf Ihren Unterarm.",
    cpr_choking_step_2: "Geben Sie 5 feste Schläge zwischen die Schulterblätter.",
    cpr_choking_step_3: "Drehen Sie das Baby um und geben Sie 5 schnelle Brustkompressionen.",
    cpr_choking_step_4: "Wiederholen Sie dies, bis das Objekt entfernt ist.",
    cpr_cpr_title: "Herz-Lungen-Wiederbelebung (HLW)",
    cpr_cpr_desc: "Wenn das Baby nicht atmet, beginnen Sie mit der HLW.",
    cpr_cpr_ratio: "Zyklus: 5 Beatmungen, dann 15 Kompressionen / 2 Beatmungen",
    cpr_cpr_step_1: "Beginnen Sie mit 5 Beatmungen (Mund und Nase abdecken).",
    cpr_cpr_step_2: "Geben Sie 15 Brustkompressionen in der Mitte der Brust.",
    cpr_cpr_step_3: "Geben Sie 2 Beatmungen. Wiederholen Sie 15:2.",
    cpr_emergency_title: "Notruf",
    cpr_emergency_desc: "Wählen Sie in Europa 112. Stellen Sie auf Lautsprecher.",
    cpr_disclaimer: "Dieser Leitfaden dient zur Information. Ein Erste-Hilfe-Kurs wird empfohlen.",
    
    guide_babywearing_title: "Ergonomisches Tragen",
    guide_babywearing_subtitle: "Hände frei, Herz nah",
    wearing_intro: "Tragen macht das Leben leichter, muss aber ergonomisch sein.",
    wearing_ergo_title: "Korrekte Haltung",
    wearing_ergo_desc: "Goldene Regeln für sicheres Tragen:",
    wearing_ergo_m: "Knie höher als der Po ('M'-Form).",
    wearing_ergo_c: "Rücken sollte die natürliche 'C'-Kurve beibehalten.",
    wearing_ergo_kiss: "Kinn darf die Brust nicht berühren (Atemwege frei).",
    wearing_types_title: "Arten von Tragetüchern",
    wearing_type_wrap_title: "Elastisches Tragetuch",
    wearing_type_wrap_desc: "Ideal für Neugeborene.",
    wearing_type_backpack_title: "Ergonomische Trage",
    wearing_type_backpack_desc: "Einfach anzuziehen. Steg von Knie zu Knie.",
    wearing_type_ring_title: "Ring Sling",
    wearing_type_ring_desc: "Asymmetrisch, toll für kurze Zeit.",
    wearing_warning_title: "Achtung",
    wearing_warning_desc: "Vermeiden Sie nach vorn gerichtete Tragen.",

    guide_blw_title: "BLW Beikost",
    guide_blw_subtitle: "Baby-Led Weaning",
    blw_intro: "BLW fördert die Autonomie und motorischen Fähigkeiten.",
    blw_requisites_title: "Voraussetzungen",
    blw_requisites_desc: "Das Baby muss diese drei Meilensteine erreichen:",
    blw_req_1: "Kann (fast) ohne Unterstützung sitzen.",
    blw_req_2: "Zungenstoßreflex ist verschwunden.",
    blw_req_3: "Zeigt aktives Interesse an Essen.",
    blw_gagging_title: "Würgen vs Verschlucken",
    blw_gagging_desc: "Den Unterschied zu kennen, gibt Ihnen Sicherheit.",
    blw_arcada_title: "Würgen (Normal & Sicher)",
    blw_arcada_desc: "Baby macht Geräusche, hustet. NICHT eingreifen.",
    blw_choking_title: "Verschlucken (Gefahr)",
    blw_choking_desc: "Kein Geräusch, Baby wird blau. Sofortiges Eingreifen nötig.",
    blw_cuts_title: "Sichere Schnitte",
    blw_cuts_desc: "Stücke sollten so groß sein wie Ihr Zeigefinger.",
    blw_cuts_1: "Weiche Lebensmittel (können mit Fingern zerdrückt werden).",
    blw_cuts_2: "Vermeiden: Wurstscheiben, ganze Trauben, Nüsse, Honig.",

    guide_signing_title: "Babyzeichensprache",
    guide_signing_subtitle: "Frühe Kommunikation",
    sign_intro: "Bringen Sie Gesten bei, um Frustration vor dem Sprechenlernen zu reduzieren.",
    sign_why_title: "Warum es funktioniert",
    sign_why_desc: "Motorik der Hände entwickelt sich vor den Stimmbändern.",
    sign_why_quote: "Ein Baby, das nach Milch zeigen kann, muss nicht danach weinen.",
    sign_basic_title: "Erste Zeichen",
    sign_milk_title: "Milch",
    sign_milk_desc: "Faust wiederholt öffnen und schließen.",
    sign_more_title: "Mehr",
    sign_more_desc: "Fingerspitzen beider Hände zusammenführen.",
    sign_eat_title: "Essen",
    sign_eat_desc: "Zusammengeführte Finger zum Mund führen.",
    sign_tips_title: "Tipps für den Erfolg",
    sign_tip_1: "Wiederholen Sie das Zeichen bei jedem Sprechen.",
    sign_tip_2: "Im Kontext verwenden.",
    sign_tip_3: "Geduldig sein."
  },
  it: {
    guide_cpr_title: "Sicurezza e RCP",
    guide_cpr_subtitle: "Protocolli Vitali",
    cpr_intro: "Nessuno vuole pensare alle emergenze, ma essere preparati salva delle vite.",
    cpr_choking_title: "Soffocamento (Heimlich Lattanti)",
    cpr_choking_desc: "Se il bambino non riesce a tossire, piangere o respirare, agisci subito.",
    cpr_choking_step_1: "Posiziona il bambino a faccia in giù sull'avambraccio.",
    cpr_choking_step_2: "Dai 5 colpi decisi tra le scapole.",
    cpr_choking_step_3: "Giralo e fai 5 compressioni rapide sul petto con due dita.",
    cpr_choking_step_4: "Ripeti fino all'espulsione dell'oggetto.",
    cpr_cpr_title: "Rianimazione Cardiopolmonare (RCP)",
    cpr_cpr_desc: "Se il bambino non respira, inizia la RCP.",
    cpr_cpr_ratio: "Ciclo: 5 ventilazioni, poi 15 compressioni / 2 ventilazioni",
    cpr_cpr_step_1: "Inizia con 5 ventilazioni (bocca-bocca/naso).",
    cpr_cpr_step_2: "Fai 15 compressioni al centro del petto.",
    cpr_cpr_step_3: "Fai 2 ventilazioni. Ripeti 15:2.",
    cpr_emergency_title: "Chiamata di Emergenza",
    cpr_emergency_desc: "In Europa chiama il 112. Usa il vivavoce.",
    cpr_disclaimer: "Questa guida è informativa. Si consiglia un corso di primo soccorso.",
    
    guide_babywearing_title: "Portare in Fascia",
    guide_babywearing_subtitle: "Mani Libere, Cuore Vicino",
    wearing_intro: "Il babywearing facilita la vita, ma deve essere ergonomico.",
    wearing_ergo_title: "Postura Corretta",
    wearing_ergo_desc: "Regole d'oro per portare in sicurezza:",
    wearing_ergo_m: "Ginocchia più alte del sedere (forma a 'M').",
    wearing_ergo_c: "La schiena deve mantenere la sua curva a 'C'.",
    wearing_ergo_kiss: "Il mento non deve toccare il petto (vie aeree libere).",
    wearing_types_title: "Tipi di Marsupi",
    wearing_type_wrap_title: "Fascia Elastica",
    wearing_type_wrap_desc: "Ideale per i neonati.",
    wearing_type_backpack_title: "Marsupio Ergonomico",
    wearing_type_backpack_desc: "Facile da indossare. Il pannello deve andare da ginocchio a ginocchio.",
    wearing_type_ring_title: "Fascia ad Anelli",
    wearing_type_ring_desc: "Asimmetrica, ottima per tempi brevi.",
    wearing_warning_title: "Attenzione",
    wearing_warning_desc: "Evita marsupi rivolti verso il mondo non ergonomici.",

    guide_blw_title: "Alimentazione Autosvezzamento",
    guide_blw_subtitle: "Baby-Led Weaning",
    blw_intro: "L'autosvezzamento favorisce l'autonomia e un sano rapporto col cibo.",
    blw_requisites_title: "Requisiti",
    blw_requisites_desc: "Il bambino deve soddisfare questi tre requisiti:",
    blw_req_1: "Riesce a stare seduto da solo.",
    blw_req_2: "Ha perso il riflesso di estrusione.",
    blw_req_3: "Mostra interesse per il cibo.",
    blw_gagging_title: "Riflesso Faringeo vs Soffocamento",
    blw_gagging_desc: "Saperli distinguere ti darà tranquillità.",
    blw_arcada_title: "Riflesso Faringeo (Normale)",
    blw_arcada_desc: "Fa rumore, tossisce, diventa rosso. NON interferire.",
    blw_choking_title: "Soffocamento (Pericolo)",
    blw_choking_desc: "Nessun rumore, diventa blu. Richiede intervento immediato.",
    blw_cuts_title: "Tagli Sicuri",
    blw_cuts_desc: "All'inizio, i pezzi devono essere grandi come un tuo dito.",
    blw_cuts_1: "Cibi morbidi (si schiacciano tra le dita).",
    blw_cuts_2: "Da evitare: wurstel a rondelle, uva intera, noci intere, miele.",

    guide_signing_title: "Segni per Bambini",
    guide_signing_subtitle: "Comunicazione Precoce",
    sign_intro: "Insegna dei gesti per ridurre la frustrazione prima che sappiano parlare.",
    sign_why_title: "Perché funziona",
    sign_why_desc: "Il controllo motorio delle mani si sviluppa prima delle corde vocali.",
    sign_why_quote: "Un bambino che può chiedere il latte con le mani non ha bisogno di piangere.",
    sign_basic_title: "Primi Segni",
    sign_milk_title: "Latte",
    sign_milk_desc: "Aprire e chiudere il pugno.",
    sign_more_title: "Ancora",
    sign_more_desc: "Unire la punta delle dita di entrambe le mani.",
    sign_eat_title: "Mangiare",
    sign_eat_desc: "Portare la mano unita verso la bocca.",
    sign_tips_title: "Consigli",
    sign_tip_1: "Ripeti il segno quando dici la parola.",
    sign_tip_2: "Usa il contesto.",
    sign_tip_3: "Sii paziente."
  },
  pt: {
    guide_cpr_title: "Segurança e RCP",
    guide_cpr_subtitle: "Protocolos Vitais",
    cpr_intro: "Ninguém quer pensar em emergências, mas estar preparado salva vidas.",
    cpr_choking_title: "Engasgo (Heimlich em Bebês)",
    cpr_choking_desc: "Se o bebê não consegue tossir, chorar ou respirar, aja imediatamente.",
    cpr_choking_step_1: "Coloque o bebê de bruços sobre seu antebraço.",
    cpr_choking_step_2: "Dê 5 tapinhas firmes nas costas.",
    cpr_choking_step_3: "Vire-o e faça 5 compressões rápidas no peito com dois dedos.",
    cpr_choking_step_4: "Repita até desengasgar.",
    cpr_cpr_title: "Reanimação Cardiopulmonar (RCP)",
    cpr_cpr_desc: "Se o bebê não estiver respirando, inicie a RCP.",
    cpr_cpr_ratio: "Ciclo: 5 respirações, depois 15 compressões / 2 respirações",
    cpr_cpr_step_1: "Comece com 5 respirações (cobrindo boca e nariz).",
    cpr_cpr_step_2: "Faça 15 compressões no centro do peito.",
    cpr_cpr_step_3: "Faça 2 respirações. Repita 15:2.",
    cpr_emergency_title: "Chamada de Emergência",
    cpr_emergency_desc: "Ligue para a emergência local (ex: 192 ou 112). Coloque no viva-voz.",
    cpr_disclaimer: "Este guia é informativo. Recomenda-se um curso de primeiros socorros.",
    
    guide_babywearing_title: "Sling e Carregadores",
    guide_babywearing_subtitle: "Mãos Livres, Coração Perto",
    wearing_intro: "Carregar o bebê facilita a vida, mas deve ser ergonômico.",
    wearing_ergo_title: "Postura Correta",
    wearing_ergo_desc: "Regras de ouro do sling seguro:",
    wearing_ergo_m: "Joelhos mais altos que o bumbum (forma de 'M').",
    wearing_ergo_c: "As costas devem manter sua curva em 'C'.",
    wearing_ergo_kiss: "O queixo não deve tocar o peito (vias livres).",
    wearing_types_title: "Tipos de Carregadores",
    wearing_type_wrap_title: "Sling Elástico (Wrap)",
    wearing_type_wrap_desc: "Ideal para recém-nascidos.",
    wearing_type_backpack_title: "Mochila Ergonômica",
    wearing_type_backpack_desc: "Fácil de vestir. O painel deve ir de joelho a joelho.",
    wearing_type_ring_title: "Sling de Argolas",
    wearing_type_ring_desc: "Assimétrico, ótimo para pouco tempo.",
    wearing_warning_title: "Atenção",
    wearing_warning_desc: "Evite mochilas não ergonômicas viradas para a frente.",

    guide_blw_title: "Introdução BLW",
    guide_blw_subtitle: "Baby-Led Weaning",
    blw_intro: "O BLW promove autonomia e uma relação saudável com a comida.",
    blw_requisites_title: "Requisitos",
    blw_requisites_desc: "O bebê deve atingir estes três marcos:",
    blw_req_1: "Consegue sentar sem apoio.",
    blw_req_2: "Perdeu o reflexo de extrusão.",
    blw_req_3: "Mostra interesse pela comida.",
    blw_gagging_title: "Reflexo de GAG vs Engasgo",
    blw_gagging_desc: "Saber a diferença traz tranquilidade.",
    blw_arcada_title: "Reflexo de GAG (Normal)",
    blw_arcada_desc: "O bebê faz barulho, tosse, fica vermelho. NÃO interfira.",
    blw_choking_title: "Engasgo (Perigo)",
    blw_choking_desc: "Sem barulho, fica azul. Requer manobra de Heimlich imediata.",
    blw_cuts_title: "Cortes Seguros",
    blw_cuts_desc: "Os pedaços devem ser grandes, como seu dedo indicador.",
    blw_cuts_1: "Alimentos macios (podem ser esmagados com os dedos).",
    blw_cuts_2: "Evite: salsichas em rodelas, uvas inteiras, nozes, mel.",

    guide_signing_title: "Linguagem de Sinais",
    guide_signing_subtitle: "Comunicação Precoce",
    sign_intro: "Ensine gestos para reduzir a frustração antes de começarem a falar.",
    sign_why_title: "Por que funciona",
    sign_why_desc: "O controle motor das mãos se desenvolve antes das cordas vocais.",
    sign_why_quote: "Um bebê que pode pedir leite com as mãos não precisa chorar por ele.",
    sign_basic_title: "Primeiros Sinais",
    sign_milk_title: "Leite",
    sign_milk_desc: "Abrir e fechar o punho repetidamente.",
    sign_more_title: "Mais",
    sign_more_desc: "Juntar as pontas dos dedos das duas mãos.",
    sign_eat_title: "Comer",
    sign_eat_desc: "Levar os dedos juntos até a boca.",
    sign_tips_title: "Dicas",
    sign_tip_1: "Repita o sinal toda vez que falar a palavra.",
    sign_tip_2: "Use em contexto.",
    sign_tip_3: "Seja paciente."
  }
};

for (const lang of Object.keys(rawKeys)) {
  const data = rawKeys[lang];
  let lines = [];
  for (const k in data) {
    const val = data[k].replace(/"/g, '\\"').replace(/\n/g, '\\n');
    lines.push("    " + k + ': "' + val + '",');
  }
  const str = "\\n" + lines.join("\\n");
  const pattern = new RegExp("(^\\\\s*" + lang + ":\\\\s*\\\\{\\\\s*\\n)", "m");
  content = content.replace(pattern, "$1" + lines.join("\n") + "\n");
}

fs.writeFileSync(file, content, 'utf8');
console.log("Updated guide translations successfully.");
